services:
  - docker

env:
  - TAG="4.4"       VERSION="4.4"
  - TAG="4.4-demo"  VERSION="4.4"       DEMO_VERSION="4.0"
  - TAG="4.5"       VERSION="4.5.x-dev"
  - TAG="4.5-demo"  VERSION="4.5.x-dev" DEMO_VERSION="4.1"
  - TAG="4.6"       VERSION="4.6.x-dev"
  - TAG="4.6-demo"  VERSION="4.6.x-dev" DEMO_VERSION="4.2"
  - TAG="4.8"       VERSION="4.8"
  - TAG="4.8-demo"  VERSION="4.8"       DEMO_VERSION="4.3"

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - echo "Build image ${DOCKER_USERNAME}/${IMAGE}:${TAG}"
  - docker image build --build-arg VERSION=${VERSION} --build-arg DEMO_VERSION=${DEMO_VERSION} -t ${DOCKER_USERNAME}/${IMAGE}:${TAG} .
  - docker image build --build-arg VERSION=${VERSION} --build-arg DEMO_VERSION=${DEMO_VERSION} --build-arg PHP_FPM_VERSION=7.3 -f alpine/Dockerfile -t ${DOCKER_USERNAME}/${IMAGE}:${TAG}-alpine .

after_success:
  - docker push ${DOCKER_USERNAME}/${IMAGE}:${TAG}
  - docker push ${DOCKER_USERNAME}/${IMAGE}:${TAG}-alpine
