services:
  - docker

env:
  - VERSION=4.4
  - VERSION=4.4 DEMO_VERSION="4.0"
  - VERSION=4.5
  - VERSION=4.5 DEMO_VERSION="4.1"
  - VERSION=4.6
  - VERSION=4.6 DEMO_VERSION="4.2"
  - VERSION=4.8
  - VERSION=4.8 DEMO_VERSION="4.3"

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - >
    if [ -n "${DEMO_VERSION}" ]; then
      export TAG=${VERSION}-demo;
    else
      export TAG=${VERSION};
    fi

script:
  - echo "Build image ${DOCKER_USERNAME}/${IMAGE}:${TAG}"
  - docker build --build-arg VERSION=${VERSION} --build-arg DEMO_VERSION=${DEMO_VERSION} -t contao .
  - docker tag contao ${DOCKER_USERNAME}/${IMAGE}:${TAG}
  - docker images

after_success:
  - docker push ${DOCKER_USERNAME}/${IMAGE}:${TAG}
