mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${password}
      MYSQL_USER: ${user}
      MYSQL_PASSWORD: ${password}
      DEFAULT_PASSWORD: ${password}
      MYSQL_DATABASE: ${database}

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
    - "mysql:mysql"
    ports:
      - "8080:80"

contao:
    image: psitrax/contao
    container_name: contao
    links:
        - "mysql:mysql"
    ports:
        - "80:80"
    volumes:
        - ./workspace:/var/www/html/src
