mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./mysql_data/:/var/lib/mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${password}
      MYSQL_DATABASE: ${database}
      MYSQL_USER: conta
      MYSQL_PASSWORD: ${password}
      DEFAULT_PASSWORD: ${password}
      
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports: 
      - "8080:80"
    links:
      - mysql
    depends_on:
      - mysql

Contao:
    image: hojak/contao:4.4-manager 
    container_name: contao
    ports:
      - "8080:80"
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - html_content:/var/www/html
