version: '3'

services:
  contao:
    image: fkasy/contao
    container_name: contao
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
    - mysql
    links:
    - "mysql:mysql"
    ports:
    - "80:80"
    volumes:
    - ./files:/var/www/html/files #files directory for working in Contao-project, e.g. css, javascript, images etc.
    - ./src:/var/www/html/src #src directory for extension development including a base-bundle for Contao 4

#Using MySql 5.7 'cause latest image results in error while setting up db in Contao Installtool
  mysql:
    image: mysql:5.7
    container_name: mysql_2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
    - "mysql:db"
    ports:
    - "8080:80"